### ISSUE TITLE
error after run npm start : Error: spawn /Applications/Browser.html.app/Contents/MacOS/graphene ENOENT

### ISSUE THREAD

**Issue by cocodrino** [mozilla/browser.html#599]
Hi, sorry but after install the dependencies I get this error when I tye npm start

```
browser.html@0.0.2 start /home/yo/Downloads/play/play-2.2.0/clojureP/browser.html/shit/browser.html
> gulp develop

[23:02:37] Using gulpfile ~/Downloads/play/play-2.2.0/clojureP/browser.html/shit/browser.html/gulpfile.js
[23:02:37] Starting 'watcher'...
[23:02:37] Finished 'watcher' after 88 μs
[23:02:37] Starting 'browser/index'...
[23:02:37] Starting 'service/history-worker'...
[23:02:37] Starting 'about/settings/index'...
[23:02:37] Starting 'server'...
[23:02:37] Finished 'server' after 30 ms
[23:02:37] Starting 'application'...
[23:02:37] Finished 'application' after 5.2 ms
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn /Applications/Browser.html.app/Contents/MacOS/graphene ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3

npm ERR! Linux 3.2.0-87-generic
npm ERR! argv "node" "/home/yo/.linuxbrew/bin/npm" "start"
npm ERR! node v0.12.2
npm ERR! npm  v2.13.1
npm ERR! code ELIFECYCLE
npm ERR! browser.html@0.0.2 start: `gulp develop`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the browser.html@0.0.2 start script 'gulp develop'.
npm ERR! This is most likely a problem with the browser.html package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp develop
npm ERR! You can get their info via:
npm ERR!     npm owner ls browser.html
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/yo/Downloads/play/play-2.2.0/clojureP/browser.html/shit/browser.html/npm-debug.log
```

I'm using linux so I don't understand why appear in the error MacOS, thanks

**Comment by jtrees** [comment]
I get a very similar error. Here is my output:

```
> browser.html@0.0.2 start ~/Archive/src/browser.html
> gulp develop

[12:25:21] Using gulpfile ~/Archive/src/browser.html/gulpfile.js
[12:25:21] Starting 'watcher'...
[12:25:21] Finished 'watcher' after 64 μs
[12:25:21] Starting 'browser/index'...
[12:25:21] Starting 'service/history-worker'...
[12:25:21] Starting 'about/settings/index'...
[12:25:21] Starting 'server'...
[12:25:21] Finished 'server' after 2.92 ms
[12:25:21] Starting 'application'...
execvp(): No such file or directory
[12:25:21] Finished 'application' after 2.83 ms

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)
npm ERR! weird error 8
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! not ok code 0
```

Any ideas?

**Comment by cocodrino** [comment]
I read this

```js 
Browser.html needs a special build of B2G desktop called Graphene. Build this branch: https://hg.mozilla.org/projects/larch with --enable-application=b2g/graphene.

In the future, we want browser.html to be able to run on top of Servo.```

I'd appreciate some guidance about what I need build and how because that brach seems include several mozilla projects.

@jtrees can you try 
```js
npm install npm -g and npm cache clean...

```

and retry,that seems to be a typical problem with npm in windows, maybe that could works.also you need build graphene (in windows I've not idea about how do it, I'm on linux)

**Comment by paulrouget** [comment]
You need to build the larch branch with `--enable-application=b2g/graphene`.

**Comment by Gozala** [comment]
I'm afraid all the development so far goes on OSX so we have not tried to configure paths build tasks to handle other OSs. I would welcome a pull request that would try to handle other OS's.

That being said one still needs a build of b2g/graphene that can be created as pointed out above by @paulrouget

**Comment by wehlutyk** [comment]
@jtrees running in Servo (as per the [current instructions](https://github.com/mozilla/browser.html#running-in-servo) in readme, where you run the server and client separately) works fine on Linux though, it's only the `application` task that fails because it has the wrong path for the browser runtime.
