### ISSUE TITLE
Hitting enter in browser.html input causes Servo to panic

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#754]
@paulrouget are you already looking into this?

```bash
thread 'ScriptTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:367
stack backtrace:
   1:        0x10dc7bac8 - sys::backtrace::tracing::imp::write::h3ed615ef3cda9b6b7It
   2:        0x10dc7dc0f - panicking::log_panic::_<closure>::closure.40650
   3:        0x10dc7d6b2 - panicking::log_panic::hdfd4a4ec7b55d6a5MAx
   4:        0x10dc68ba6 - sys_common::unwind::begin_unwind_inner::h2f70decd24e7a2917Ls
   5:        0x10dc68f8e - sys_common::unwind::begin_unwind_fmt::h29da0d611b24747ddLs
   6:        0x10dc7b0e7 - rust_begin_unwind
   7:        0x10dca0270 - panicking::panic_fmt::h2f3428e3725b99d6VFK
   8:        0x10dca056c - panicking::panic::h72b18290823e7468sEK
   9:        0x10c583b02 - option::_<impl>::unwrap::unwrap::h6960422550996673363
  10:        0x10c582bb0 - timers::_<impl>::fire_timer::h158693379356558510
  11:        0x10c5826cd - dom::window::_<impl>::handle_fire_timer::h75e4eb2adce88baaLsU
  12:        0x10c678812 - script_task::_<impl>::handle_timer_event::hf851b781d4813ac0J8Y
  13:        0x10c6767ab - script_task::_<impl>::handle_msgs::_<closure>::closure.160862
  14:        0x10c6762f2 - script_task::_<impl>::profile_event::h12198904388542953316
  15:        0x10c648e39 - script_task::_<impl>::handle_msgs::h07e910787e7b88e2QTY
  16:        0x10c5f3a10 - script_task::_<impl>::start::h37b2c4bbfb5227a8GTY
  17:        0x10c5f39c4 - script_task::_<impl>::create::_<closure>::_<closure>::closure.159576
  18:        0x10c5f3730 - mem::_<impl>::run_with_memory_reporting::run_with_memory_reporting::h16408896450759701848
  19:        0x10c5dddbf - script_task::_<impl>::create::_<closure>::closure.158954
  20:        0x10c5dd197 - util::task::spawn_named_with_send_on_failure::_<closure>::closure.158941
  21:        0x10c5dcb83 - std::thread::_<impl>::spawn::_<closure>::_<closure>::closure.158930
  22:        0x10c5dcaf8 - sys_common::unwind::try::try_fn::try_fn::h17308395060509038760
  23:        0x10dc7af08 - __rust_try
  24:        0x10dc7800e - sys_common::unwind::try::inner_try::hd7e4f8fc422767d2FIs
  25:        0x10c5dca35 - sys_common::unwind::try::try::h9775299089309158069
  26:        0x10c5dc86e - std::thread::_<impl>::spawn::_<closure>::closure.158927
  27:        0x10c5dd3b7 - boxed::_<impl>::call_box::call_box::h8710042237404481650
  28:        0x10dc7ce9d - sys::thread::_<impl>::new::thread_start::ha2c46efb1706c462jVw
  29:     0x7fff976a1059 - _pthread_body
  30:     0x7fff976a0fd6 - _pthread_start
thread 'Constellation' panicked at 'unable to find pipeline - this is a bug', ../src/libcore/option.rs:335
stack backtrace:
thread 'PaintTask PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("recursive IPC channel use during serialization") }) }', ../src/libcore/result.rs:741
   1:        0x10dc7bac8 - sys::backtrace::tracing::imp::write::h3ed615ef3cda9b6b7It
thread 'LayoutTask PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("MPSC send failed") }) }', ../src/libcore/result.rs:741
   2:        0x10dc7dc0f - panicking::log_panic::_<closure>::closure.40650
   3:        0x10dc7d6b2 - panicking::log_panic::hdfd4a4ec7b55d6a5MAx
   4:        0x10dc68ba6 - sys_common::unwind::begin_unwind_inner::h2f70decd24e7a2917Ls
   5:        0x10dc68f8e - sys_common::unwind::begin_unwind_fmt::h29da0d611b24747ddLs
   6:        0x10dc7b0e7 - rust_begin_unwind
   7:        0x10dca0270 - panicking::panic_fmt::h2f3428e3725b99d6VFK
   8:        0x10b4d54df - option::_<impl>::expect::expect::h5981153219404430554
   9:        0x10b59bb88 - constellation::_<impl>::handle_failure_msg::handle_failure_msg::h13889768469295686747
  10:        0x10b4665fa - constellation::_<impl>::handle_request::handle_request::h3504824828587142847
  11:        0x10b4634bc - constellation::_<impl>::run::run::h16423323877102525830
thread 'PaintTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("recursive IPC channel use during serialization") }) }', ../src/libcore/result.rs:741
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', ../src/libcore/result.rs:741
  12:        0x10b4480d0 - export::compositing::constellation::_<impl>::start::_<closure>::closure.23365
  13:        0x10b4463a3 - std::thread::_<impl>::spawn::_<closure>::_<closure>::closure.23354
  14:        0x10b446318 - sys_common::unwind::try::try_fn::try_fn::h9498399356807041057
  15:        0x10dc7af08 - __rust_try
  16:        0x10dc7800e - sys_common::unwind::try::inner_try::hd7e4f8fc422767d2FIs
  17:        0x10b446255 - sys_common::unwind::try::try::h7833021402856884290
  18:        0x10b44608e - std::thread::_<impl>::spawn::_<closure>::closure.23331
  19:        0x10b448377 - boxed::_<impl>::call_box::call_box::h6699689534649897737
  20:        0x10dc7ce9d - sys::thread::_<impl>::new::thread_start::ha2c46efb1706c462jVw
  21:     0x7fff976a1059 - _pthread_body
  22:     0x7fff976a0fd6 - _pthread_start
stack backtrace:
   1:        0x10dc7bac8 - sys::backtrace::tracing::imp::write::h3ed615ef3cda9b6b7It
   2:        0x10dc7dc0f - panicking::log_panic::_<closure>::closure.40650
   3:        0x10dc7d6b2 - panicking::log_panic::hdfd4a4ec7b55d6a5MAx
   4:        0x10dc68ba6 - sys_common::unwind::begin_unwind_inner::h2f70decd24e7a2917Ls
   5:        0x10dc68f8e - sys_common::unwind::begin_unwind_fmt::h29da0d611b24747ddLs
   6:        0x10dc7b0e7 - rust_begin_unwind
   7:        0x10dca0270 - panicking::panic_fmt::h2f3428e3725b99d6VFK
   8:        0x10c7e9756 - result::_<impl>::unwrap::unwrap::h1463798665268746872
   9:        0x10c8c85be - gfx::paint_task::_<impl>::create::_<closure>::closure.33017
  10:        0x10c8c7847 - util::task::spawn_named_with_send_on_failure::_<closure>::closure.33004
  11:        0x10c8c7233 - std::thread::_<impl>::spawn::_<closure>::_<closure>::closure.32993
  12:        0x10c8c71a8 - sys_common::unwind::try::try_fn::try_fn::h7837917924088147048
  13:        0x10dc7af08 - __rust_try
  14:        0x10dc7800e - sys_common::unwind::try::inner_try::hd7e4f8fc422767d2FIs
  15:        0x10c8c70e5 - sys_common::unwind::try::try::h3910354230953057230
  16:        0x10c8c6f1e - std::thread::_<impl>::spawn::_<closure>::closure.32990
  17:        0x10c8c7a67 - boxed::_<impl>::call_box::call_box::h12744356009850992270
  18:        0x10dc7ce9d - sys::thread::_<impl>::new::thread_start::ha2c46efb1706c462jVw
  19:     0x7fff976a1059 - _pthread_body
  20:     0x7fff976a0fd6 - _pthread_start
stack backtrace:
   1:        0x10dc7bac8 - sys::backtrace::tracing::imp::write::h3ed615ef3cda9b6b7It
   2:        0x10dc7dc0f - panicking::log_panic::_<closure>::closure.40650
   3:        0x10dc7d6b2 - panicking::log_panic::hdfd4a4ec7b55d6a5MAx
   4:        0x10dc68ba6 - sys_common::unwind::begin_unwind_inner::h2f70decd24e7a2917Ls
   5:        0x10dc68f8e - sys_common::unwind::begin_unwind_fmt::h29da0d611b24747ddLs
   6:        0x10dc7b0e7 - rust_begin_unwind
   7:        0x10dca0270 - panicking::panic_fmt::h2f3428e3725b99d6VFK
   8:        0x10b6417e6 - result::_<impl>::unwrap::unwrap::h7033438661407417669
   9:        0x10b870ccb - layout_task::_<impl>::exit_now::h75770fb066fd22f4WLq
  10:        0x10b870ba6 - layout_task::_<impl>::prepare_to_exit::h29e2db567f0b263b4Jq
  11:        0x10b8419c6 - layout_task::_<impl>::handle_request_helper::h33098a79dcb1fdb1kBq
  12:        0x10b8197d5 - layout_task::_<impl>::handle_request::h3dc891386b0fe1cfKvq
  13:        0x10b7e5b6a - layout_task::_<impl>::start::ha974aac97fa99c800tq
  14:        0x10b7e59b7 - layout_task::_<impl>::create::_<closure>::_<closure>::closure.54926
  15:        0x10b7dfb83 - mem::_<impl>::run_with_memory_reporting::run_with_memory_reporting::h3478078334660652444
  16:        0x10b7aa500 - layout_task::_<impl>::create::_<closure>::closure.53214
  17:        0x10b7a9907 - util::task::spawn_named_with_send_on_failure::_<closure>::closure.53185
  18:        0x10b7a92f3 - std::thread::_<impl>::spawn::_<closure>::_<closure>::closure.53174
  19:        0x10b7a9268 - sys_common::unwind::try::try_fn::try_fn::h9642013877653872772
  20:        0x10dc7af08 - __rust_try
  21:        0x10dc7800e - sys_common::unwind::try::inner_try::hd7e4f8fc422767d2FIs
  22:        0x10b7a91a5 - sys_common::unwind::try::try::h2792156776491876035
  23:        0x10b7a8fde - std::thread::_<impl>::spawn::_<closure>::closure.53151
  24:        0x10b7a9b67 - boxed::_<impl>::call_box::call_box::h2157169286100682099
  25:        0x10dc7ce9d - sys::thread::_<impl>::new::thread_start::ha2c46efb1706c462jVw
  26:     0x7fff976a1059 - _pthread_body
  27:     0x7fff976a0fd6 - _pthread_start
stack backtrace:
   1:        0x10dc7bac8 - sys::backtrace::tracing::imp::write::h3ed615ef3cda9b6b7It
   2:        0x10dc7dc0f - panicking::log_panic::_<closure>::closure.40650
   3:        0x10dc7d6b2 - panicking::log_panic::hdfd4a4ec7b55d6a5MAx
   4:        0x10dc68ba6 - sys_common::unwind::begin_unwind_inner::h2f70decd24e7a2917Ls
   5:        0x10dc68f8e - sys_common::unwind::begin_unwind_fmt::h29da0d611b24747ddLs
   6:        0x10dc7b0e7 - rust_begin_unwind
   7:        0x10dca0270 - panicking::panic_fmt::h2f3428e3725b99d6VFK
   8:        0x10c7e9756 - result::_<impl>::unwrap::unwrap::h1463798665268746872
   9:        0x10c8c85be - gfx::paint_task::_<impl>::create::_<closure>::closure.33017
  10:        0x10c8c7847 - util::task::spawn_named_with_send_on_failure::_<closure>::closure.33004
  11:        0x10c8c7233 - std::thread::_<impl>::spawn::_<closure>::_<closure>::closure.32993
  12:        0x10c8c71a8 - sys_common::unwind::try::try_fn::try_fn::h7837917924088147048
  13:        0x10dc7af08 - __rust_try
  14:        0x10dc7800e - sys_common::unwind::try::inner_try::hd7e4f8fc422767d2FIs
  15:        0x10c8c70e5 - sys_common::unwind::try::try::h3910354230953057230
  16:        0x10c8c6f1e - std::thread::_<impl>::spawn::_<closure>::closure.32990
  17:        0x10c8c7a67 - boxed::_<impl>::call_box::call_box::h12744356009850992270
  18:        0x10dc7ce9d - sys::thread::_<impl>::new::thread_start::ha2c46efb1706c462jVw
  19:     0x7fff976a1059 - _pthread_body
  20:     0x7fff976a0fd6 - _pthread_start
stack backtrace:
   1:        0x10dc7bac8 - sys::backtrace::tracing::imp::write::h3ed615ef3cda9b6b7It
   2:        0x10dc7dc0f - panicking::log_panic::_<closure>::closure.40650
   3:        0x10dc7d6b2 - panicking::log_panic::hdfd4a4ec7b55d6a5MAx
   4:        0x10dc68ba6 - sys_common::unwind::begin_unwind_inner::h2f70decd24e7a2917Ls
   5:        0x10dc68f8e - sys_common::unwind::begin_unwind_fmt::h29da0d611b24747ddLs
   6:        0x10dc7b0e7 - rust_begin_unwind
   7:        0x10dca0270 - panicking::panic_fmt::h2f3428e3725b99d6VFK
   8:        0x10b39174a - result::_<impl>::unwrap::unwrap::h3871956075089809803
   9:        0x10b385c0b - compositor::_<impl>::send_buffer_requests_for_all_layers::send_buffer_requests_for_all_layers::h6126165461902280687
  10:        0x10b32328c - compositor::_<impl>::handle_browser_message::handle_browser_message::h6063764970392588850
  11:        0x10b320c22 - compositor::_<impl>::handle_events::handle_events::h11802534937599162251
  12:        0x10b3e4d88 - _<impl>::handle_events::h4b4e09e77bca653fTda
  13:        0x10b2e51ac - main::hb77cfbfb032d8741Laa
  14:        0x10dc7d432 - sys_common::unwind::try::try_fn::h15039379299886391
  15:        0x10dc7af08 - __rust_try
  16:        0x10dc7d2d9 - rt::lang_start::hb609b9e4718008c7Uxx
  17:        0x10b3d7869 - main
Servo exited with return value 101
```

**Comment by gordonbrander** [comment]
Commenting out https://github.com/mozilla/browser.html/blob/perspective-ui/src/browser/input.js#L174 prevents crasher from happening.

**Comment by paulrouget** [comment]
I'll look at this today.

**Comment by paulrouget** [comment]
I can't reproduce. Any specific STR? Did you manage to get a minimal test case?

**Comment by gordonbrander** [comment]
no, I've not been able to create a test case :/

**Comment by gordonbrander** [comment]
This is no longer the case in WebRender builds.
